fix hanging e2e tests
when using timeout without foreground option, docker hangs because it tries
to write to the tty.

diff --git a/t/devbox/Makefile b/t/devbox/Makefile
--- a/t/devbox/Makefile
+++ b/t/devbox/Makefile
@@ -2,25 +2,35 @@
 SHELL=bash
 .PHONY: test lmd_build provision
 
+INTERACTIVE:=$(shell [ -t 0 ] && echo 1)
+ifdef INTERACTIVE
+  DOCKER_COMPOSE_TTY=
+  DOCKER_COMPOSE_LOGS=
+else
+  DOCKER_COMPOSE_TTY=-T
+  DOCKER_COMPOSE_LOGS=--no-color
+endif
+
 test: lmd_build box_prepared
-	timeout -s KILL -v 10m docker compose exec -T --user root devbox sudo -iu demo /box/tests/local_test.sh 0
+	timeout --foreground -s KILL -v 10m docker compose exec $(DOCKER_COMPOSE_TTY) --user root devbox sudo -iu demo /box/tests/local_test.sh 0
 
 test_verbose: lmd_build box_prepared
-	timeout -s KILL -v 10m docker compose exec -T --user root devbox sudo -iu demo /box/tests/local_test.sh 1
+	timeout --foreground -s KILL -v 10m docker compose exec $(DOCKER_COMPOSE_TTY) --user root devbox sudo -iu demo /box/tests/local_test.sh 1
 
 prepare:
-	timeout -s KILL -v 30m docker compose build
+	timeout --foreground -s KILL -v 30m docker compose build
 	docker compose up --remove-orphans -d
 	docker ps
-	@docker compose logs -t -f | while read LOGLINE; do \
+	@docker compose logs -t $(DOCKER_COMPOSE_LOGS) -f | while read LOGLINE; do \
 		echo "$${LOGLINE}"; \
-		[[ "$${LOGLINE}" == *"starting Apache web server"* ]] && pkill -PIPE -P $$$$ "docker" && exit 0; \
-		[[ "$${LOGLINE}" == *"ERROR"* ]]                      && pkill -PIPE -P $$$$ "docker" && exit 1; \
+		[[ "$${LOGLINE}" == *"starting Apache web server"* ]] && pkill -P $$$$ "docker" -9 && exit 0; \
+		[[ "$${LOGLINE}" == *"ERROR"* ]]                      && pkill -P $$$$ "docker" -9 && exit 1; \
+		[[ "$${LOGLINE}" == *"exited with code"* ]]           && pkill -P $$$$ "docker" -9 && exit 1; \
 	done
 	$(MAKE) provision
 
 provision:
-	timeout -s KILL -v 30m docker exec "devbox-devbox-1" env TERM=xterm bash -c "/box/provision/ansible.sh"
+	timeout --foreground -s KILL -v 30m docker exec $(DOCKER_COMPOSE_TTY) "devbox-devbox-1" env TERM=xterm bash -c "/box/provision/ansible.sh"
 
 box_prepared:
 	@[ $$(docker compose ps | grep devbox | grep Up | wc -l) -eq 1 ] || $(MAKE) prepare
