fix hanging ci tests
do not start docker exec with -i

diff --git a/t/devbox/Makefile b/t/devbox/Makefile
--- a/t/devbox/Makefile
+++ b/t/devbox/Makefile
@@ -3,24 +3,24 @@ SHELL=bash
 .PHONY: test lmd_build provision
 
 test: lmd_build box_prepared
-	docker compose exec --user root devbox sudo -iu demo /box/tests/local_test.sh 0
+	timeout -v 10m docker compose exec -T --user root devbox sudo -iu demo /box/tests/local_test.sh 0
 
 test_verbose: lmd_build box_prepared
-	docker compose exec --user root devbox sudo -iu demo /box/tests/local_test.sh 1
+	timeout -v 10m docker compose exec -T --user root devbox sudo -iu demo /box/tests/local_test.sh 1
 
 prepare:
-	docker compose build
+	timeout -v 30m docker compose build
 	docker compose up --remove-orphans -d
 	docker ps
-	@while read LOGLINE; do \
+	@docker compose logs -t -f | while read LOGLINE; do \
 		echo "$${LOGLINE}"; \
-		[[ "$${LOGLINE}" == *"starting Apache web server"* ]] && exit 0; \
-		[[ "$${LOGLINE}" == *"ERROR"* ]] && exit 1; \
-	done < <(docker compose logs -f)
+		[[ "$${LOGLINE}" == *"starting Apache web server"* ]] && pkill -PIPE -P $$$$ "docker" && exit 0; \
+		[[ "$${LOGLINE}" == *"ERROR"* ]]                      && pkill -PIPE -P $$$$ "docker" && exit 1; \
+	done
 	$(MAKE) provision
 
 provision:
-	docker exec -i "devbox-devbox-1" env TERM=xterm bash -c "/box/provision/ansible.sh"
+	timeout -v 30m docker exec "devbox-devbox-1" env TERM=xterm bash -c "/box/provision/ansible.sh"
 
 box_prepared:
 	@[ $$(docker compose ps | grep devbox | grep Up | wc -l) -eq 1 ] || $(MAKE) prepare
